### ISSUE TITLE
startup instructions

### ISSUE THREAD

**Issue by donpdonp** [macourtney/Dark-Exchange#45]
Im not familiar with clojure so I took my best shot and starting the app but got this error. Can you help and/or add README notes for starting the app?

$ git clone https://github.com/macourtney/Dark-Exchange
$ cd Dark-Exchange/
$ clojure project.clj 
Exception in thread "main" java.lang.Exception: Unable to resolve symbol: defproject in this context (project.clj:1)
    at clojure.lang.Compiler.analyze(Compiler.java:4420)
    at clojure.lang.Compiler.analyze(Compiler.java:4366)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:2828)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:4594)
    at clojure.lang.Compiler.analyze(Compiler.java:4405)
    at clojure.lang.Compiler.analyze(Compiler.java:4366)
    at clojure.lang.Compiler.eval(Compiler.java:4646)
    at clojure.lang.Compiler.load(Compiler.java:4972)
    at clojure.lang.Compiler.loadFile(Compiler.java:4939)
    at clojure.main$load_script__7405.invoke(main.clj:213)
    at clojure.main$script_opt__7442.invoke(main.clj:265)
    at clojure.main$main__7466.doInvoke(main.clj:346)
    at clojure.lang.RestFn.invoke(RestFn.java:413)
    at clojure.lang.Var.invoke(Var.java:359)
    at clojure.lang.AFn.applyToHelper(AFn.java:173)
    at clojure.lang.Var.applyTo(Var.java:476)
    at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Unable to resolve symbol: defproject in this context
    at clojure.lang.Compiler.resolveIn(Compiler.java:4797)
    at clojure.lang.Compiler.resolve(Compiler.java:4743)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:4720)
    at clojure.lang.Compiler.analyze(Compiler.java:4387)
    ... 16 more

**Comment by donpdonp** [comment]
I made an edit to the wiki startup instructions to use Leningen.
