### ISSUE TITLE
 Cannot open <#<Timestamp>> as an InputStreamException when viewing an open order

### ISSUE THREAD

**Issue by donpdonp** [macourtney/Dark-Exchange#47]
I am able to create an offer and a friend found and started a trade. When I go to view a trade, in status "Needs to be confirmed", an exception is thrown:

<pre>
2011-09-07 14:01:49,263 ERROR [darkexchange.uncaught-exception-handler]: Uncaught Exception:
java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot open <#<Timestamp 2011-09-07 13:58:09.488>> as an InputStream.
    at clojure.lang.AFn.run(AFn.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

</pre>

**Comment by macourtney** [comment]
How are you running Dark Exchange? This looks like a java security issue.

**Comment by donpdonp** [comment]
Im using 'lenigen run' to start DarkExchange

**Comment by macourtney** [comment]
Did you try it after downgrading leiningen? There is an issue with the latest version of Leiningen and the most recently released version of Dark Exchange. I checked in a change to fix the issue. However, you may have to run it with 'lein run :development'.

**Comment by donpdonp** [comment]
Im using leningen 1.5 (the app doesnt even start with 1.6). I launched it with 'lein run :development'. Then it started recreating the database and running migrations. In this database I created  a new user but I dont have the example offer that causes the error. Is there a simple way to run two copies of DarkExchange on the same laptop in order to trade between them?

**Comment by macourtney** [comment]
Yes. You can use 'lein tar' to create a release of Dark Exchange for your use locally. You can untar the file anywhere you want. When you run it, use 'run.bat -mode development'.

All data will be saved to the directory you untarred the file to. If you want to save the data for later use, copy and save the data directory.
